import CartItem from "@/components/CartItem/CartItem";
import Navbar from "@/components/Navbar/Navbar";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

const Cart = ({ products }) => {

    const [storedCart, setStoredCart] = useState(null);

    useEffect(() => {
        const value = localStorage.getItem('shopping-cart');
        const cartItems = !!value ? JSON.parse(value) : undefined;
        setStoredCart(cartItems)
    }, []);

    console.log(storedCart);

    const initialCart = [];
    for (const id in storedCart) {
        const addedProduct = products.find(product => product._id === id);
        // console.log(addedProduct);
        if (addedProduct) {
            const quantity = storedCart[id];
            console.log(quantity);
            addedProduct.quantity = quantity;
            initialCart.push(addedProduct);
        }
        // console.log(addedProduct);
    }

    console.log(initialCart);



    return (
        <div>
            <Head>
                <title>E-Bazar - Cart</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/Logo/logo.png" />
            </Head>
            <Navbar />
            {
                initialCart.map(item => <CartItem
                    item={item}
                    key={item._id}
                ></CartItem>)
            }
            {
                initialCart.length === 0 && <h1
                    className="text-center text-3xl font-semibold mt-16"
                >No product added yet.</h1>
            }
            <div className="flex justify-center">
                <Link href="/checkout">
                    <button className="text-2xl py-3 w-96 mx-auto mb-3 font-medium text-white bg-[#F55E3D] hover:bg-[#FDB334] border-0">Checkout Now</button>
                </Link>
            </div>
        </div>
    );
};

export const getStaticProps = async () => {

    const res = await fetch('http://localhost:5000/products');
    const data = await res.json();

    return {
        props: {
            products: data
        }
    }

}

export default Cart;