import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import Head from "next/head";

const Checkout = () => {
    return (
        <div>

            <Head>
                <title>E-Bazar - Checkout</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/Logo/logo.png" />
            </Head>

            <Navbar />

            <div className="w-[400px] my-10 mx-auto shadow-2xl rounded-lg p-5">
                <h3 className="text-2xl text-center font-medium">SUMMERY</h3>
                <div className="flex justify-between my-3">
                    <span>Subtotal</span>
                    <span className="font-medium">$120.00</span>
                </div>
                <div className="flex justify-between my-3">
                    <span>Estimated Delivery & Handling</span>
                    <span className="font-medium">$0.00</span>
                </div>
                <div className="flex justify-between my-3">
                    <span>Taxes</span>
                    <span className="font-medium">-</span>
                </div>
                <div className="flex justify-between my-3">
                    <span>TOTAL</span>
                    <span className="font-medium">$120.00</span>
                </div>
                <button className="text-2xl rounded-lg py-3 w-full mx-auto mb-3 font-medium mt-5 text-white bg-[#F55E3D] hover:bg-[#FDB334] border-0">Pay Now</button>
            </div>

            <Footer />
        </div>
    );
};

export default Checkout;