import Navbar from '@/components/Navbar/Navbar';
import Head from 'next/head';
import React from 'react';

const Dashboard = () => {
    return (
        <div>
            <Head>
                <title>E-Bazar - Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/Logo/logo.png" />
            </Head>
            <Navbar />
            <h1 className="text-2xl w-[500px] text-center mx-auto mt-8">Dashboard for different types of user will be comming here soon. And It will be Protected route. It Interface dependes on user role.</h1>
            <h2 className="text-xl w-[500px] bg-[#F55E3D] text-white p-2 text-center mx-auto mt-8">If increase practical task time 2 or 3 days I can add multivandor role on this website in Dashboard and Can also work with UI.</h2>
        </div>
    );
};

export default Dashboard;