import Navbar from '@/components/Navbar/Navbar';
import Head from 'next/head';
import React from 'react';

const Dashboard = () => {
    return (
        <div>
            <Head>
                <title>E-Bazar - Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/Logo/logo.png" />
            </Head>
            <Navbar />
            <h1>This is Dashboard</h1>
        </div>
    );
};

export default Dashboard;